### ISSUE TITLE
sfdx-project configuration prevents from creating unlocked package

### ISSUE THREAD

**Issue by cesarzh** [developerforce/GIFter#2]
Hi, 

I was going through the trailhead (Quick Start) using the default sfdx-project.json setup but it keeps giving me the following error:
ERROR running force:package:version:create:  The Package Id: GIFter isn't defined in the sfdx-project.json. Add it to the packageDirectories section and add the alias to packageAliases with its 0Ho ID.

Apparently, the sfdx-project.json file needs to be updated...

**Comment by cesarzh** [comment]
UPDATE: SOLVED
____________________________________________
I used the following format for the sfdx-project.json

```
{
   "packageDirectories": [
      {
         "path": "force-app",
         "default": true
      }
   ],
   "namespace": "",
   "sfdcLoginUrl": "https://login.salesforce.com",
   "sourceApiVersion": "44.0"
}
```
After creating the package, the format will be changed to something like: 
```
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "dreamhouse",
            "versionName": "Version 1.0",
            "versionNumber": "1.0.0.NEXT"
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "44.0",
    "packageAliases": {
        "dreamhouse": "0Ho3X0000008OLsSAM",
    }
}
```
You can change versionName and versionNumber for the versioning as needed

**Comment by douglascayers** [comment]
Hi @cesarzh, thanks for learning about unlocked packages with the GIFter-to-Chatter project.

The latest instructions can be found at https://trailhead.salesforce.com/content/learn/projects/quick-start-unlocked-packages that walk through how to edit the configuration files to create the package.

Glad you got it working!

If you encounter issues in the future, please visit https://trailhead.salesforce.com/en/help and our support team will be happy to assist.

Thank you
